# Site settings
author: Cristina Kouri
title: 
header-img: img/home-bg.png
email: cristina.isabel.kouri@gmail.com
copyright_name: Cristina Kouri
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  cristinakouri

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
